# Generated by Django 5.0.6 on 2024-06-25 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wishlist_name", models.CharField(max_length=100)),
                ("show_users", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Wishlist",
                "verbose_name_plural": "Wishlists",
            },
        ),
        migrations.CreateModel(
            name="WishListUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_users",
                        to="core.wishlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist user",
                "verbose_name_plural": "Wishlist users",
            },
        ),
        migrations.CreateModel(
            name="Wish",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.CharField(blank=True, max_length=10, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_wishes",
                        to="core.wishlistuser",
                    ),
                ),
                (
                    "wishlist_user",
                    models.ForeignKey(
                        help_text="The wish belongs to this user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishes",
                        to="core.wishlistuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "wishes",
            },
        ),
    ]
