# Generated by Django 5.0.6 on 2024-07-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Is the user allowed to participate in the wishlist?",
            ),
        ),
    ]
