# Generated by Django 5.0.6 on 2024-07-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_wishlistuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="wish",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
