# Generated by Django 5.0.6 on 2024-08-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_wish_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="wish",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
