# Generated by Django 5.0.6 on 2024-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
