# Generated by Django 5.0.6 on 2025-02-23 16:39

from django.db import migrations
from django.db.models import Q


def add_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    users_group, _ = Group.objects.get_or_create(name="Users")

    # Add log entry and core permissions to the Users group
    permissions = Permission.objects.filter(
        Q(codename__in=["add_logentry", "change_logentry", "view_logentry"])
        | Q(content_type__app_label="core")
    )

    for permission in permissions:
        users_group.permissions.add(permission)


def remove_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get(name="Users").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_wish_price"),
    ]

    operations = [
        migrations.RunPython(
            add_groups, reverse_code=remove_groups
        )
    ]
