# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_default_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_surprise_mode_enabled',
            field=models.BooleanField(default=True),
        ),
    ]