# Generated by Django 5.0.6 on 2025-09-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_wishlist_is_surprise_mode_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlistuser",
            name="is_admin",
        ),
    ]
