# Generated by Django 5.2.6 on 2025-11-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_admin_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='suggested_by',
            field=models.ForeignKey(blank=True, help_text='The user who suggested this wish', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_wishes', to='core.wishlistuser'),
        ),
    ]
