name: Docker Image CI

on:
  workflow_run:
    workflows: [Django CI]
    types:
      - completed


jobs:
  on-success:

    runs-on: ubuntu-latest
    # Only run this job if the Django CI job was successful && this is a push to the main branch (not a pull request)
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/simplewishlist-backend:latest
        file: ./Dockerfile.production
